# Generated by Django 3.1.6 on 2021-11-30 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(default='', max_length=100)),
                ('sno', models.CharField(default=0, max_length=18)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_of_death', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('father_name', models.CharField(default='', max_length=100)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('present_holding_no', models.CharField(default='', max_length=10)),
                ('present_city', models.CharField(default='', max_length=50)),
                ('present_area_code', models.CharField(default=0, max_length=10)),
                ('present_country', models.CharField(default='Bangladesh', max_length=100)),
                ('permanent_holding_no', models.CharField(default='', max_length=10)),
                ('permanent_city', models.CharField(default='', max_length=50)),
                ('permanent_area_code', models.CharField(default=0, max_length=10)),
                ('permanent_country', models.CharField(default='Bangladesh', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
